<?php
include('dbini.php');
$query="SELECT user,first,last,email,pass FROM auth WHERE user='".$_POST["username"]."' AND pass='".$_POST["password"]."'";
$result=$mysqli->query($query);
if($result->num_rows==1)
{
$row=$result->fetch_assoc();
$pass=$row['pass'];
$user=$row['user'];
$first=$row['first'];
$last=$row['last'];
$email=$row['email'];
$id=$row['id'];
$mysqli->close();
setcookie("pass",$pass);
setcookie("user",$user);
setcookie('first',$first);
setcookie('last',$last);
setcookie('email',$email);
}
elseif(isset($_COOKIE["user"])&&isset($_COOKIE["pass"]))
{
include('dbini.php');
$query="SELECT user,first,last,email,pass FROM auth WHERE user='".$_COOKIE["user"]."' AND pass='".$_COOKIE["pass"]."'";
$result=$mysqli->query($query);
if($result->num_rows==1)
{
$row=$result->fetch_assoc();
$pass=$row['pass'];
$user=$row['user'];
$first=$row['first'];
$last=$row['last'];
$email=$row['email'];
$mysqli->close();
}
else
{
header('Location:unauth.php');
exit();
}
}
else 
{
header('Location:unauth.php');
exit();
}
?>